<!DOCTYPE html>
<html>

    <head>
        $hackageCssTheme()$
        <script src="/static/jquery.min.js"></script>
        <script src="/static/datatables/jquery.dataTables.min.js"></script>
        <link rel="stylesheet" href="/static/datatables/jquery.dataTables.min.css">
        <title>Package candidates | Hackage</title>
    </head>

<body>
  $hackagePageHeader()$
  <div id="content">
            <h1>$heading$</h1>
            $content$
            $list$
            $footer$
        </div>
</body>
</html>