<!DOCTYPE html>
<html>

    <head>
        <script src="/static/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.4/sp-1.4.0/datatables.min.css"/>
        $hackageCssTheme()$

        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.4/sp-1.4.0/datatables.min.js"></script>
        <title>Package candidates | Hackage</title>
    </head>

<body>
  $hackagePageHeader()$
  <div id="content">
            <h1>$heading$</h1>
            $content$
            $list$
            $footer$
        </div>
</body>
</html>
