<!DOCTYPE html>
<html>
<head>
$hackageCssTheme()$
<title>Auth token revoked | Hackage</title>
</head>

<body>
$hackagePageHeader()$

<div id="content">
<h2>Revoked auth token for $username$</h2>
<p>
  Your auth token was revoked and it can no longer be used for authentication.
</p>

<ul>
  <li>
    <a href="/user/$username$/manage">
      Go back to management page
    </a>
  </li>
</ul>

</div>
</body></html>
