<!DOCTYPE html>
<html>
<head>
$hackageCssTheme()$
<title>Account recovery | Hackage</title>
</head>

<body>
$hackagePageHeader()$

<div id="content">
<h2>Account recovery email sent</h2>

<p>An email has been sent to <b>$useremail$</b>

<p>The email will contain a link to a page where
you can set a new password.

<p>Note that these activation links do eventually expire,
so don't leave it too long!

</div>
</body></html>
