Dear $realname$,

We received a request to create a Hackage account
for you. To create a Hackage account, please follow
this link:

  $confirmlink$

If you were not expecting this email, our apologies,
please ignore it.

From,
  The Hackage website at $serverhost$
  (and on behalf of the site administrators)
______________________________________________
Please do not reply to this email. This email
address is used only for sending email so you
will not receive a response.

