<!DOCTYPE html>
<html>
<head>
$hackageCssTheme()$
<title>HackageDB: Register a new account</title>
</head>

<body>
$hackagePageHeader()$

<h2>Confirmation email sent</h2>

<p>An email has been sent to <b>$useremail$</b>

<p>The email will contain a link to a page where
you can set your password and activate your account.

<p>Note that these activation links do eventually expire,
so don't leave it too long!

</body></html>
