Dear $realname$,

We received a request to create a Hackage account
for you. To create a Hackage account, please follow
this link:

  $confirmlink$

After your account is created, you will need to be added to the
uploaders group in order to upload packages.

The easiest way to be added to the uploaders group is to ask two other
confirmed uploaders to endorse you, sending them the following link:

 $endorselink$

Alternately, you can email the Hackage Trustees at
hackage-trustees@haskell.org requesting addition to the uploader
group. In this email, please include your Hackage username and a link
to the package you'd like to upload (on a host like gitlab or
github). This measure is unfortunately necessary to prevent spam
accounts.

For storage and bandwidth reasons, we ask uploaders to only upload
packages they believe will be useful to others and that they intend to maintain.

If you were not expecting this email, our apologies,
please ignore it.

From,
  The Hackage website at $serverhost$
  (and on behalf of the site administrators)
______________________________________________
Please do not reply to this email. This email
address is used only for sending email so you
will not receive a response.
