<!DOCTYPE html>
<html>
<head>
$hackageCssTheme()$
<title>User accounts | Hackage</title>
</head>

<body>
$hackagePageHeader()$

<div id="content">
<h2>User accounts</h2>
<p>Most of the functions of the Hackage web interface
(including browsing and checking packages) are available to all.
However, uploading packages requires a Hackage username and password.
</p>

<p>So, you can <a href="/users/register-request">register a new user account</a>.</p>

<p>You can also peruse the <a href="/users/">list of users</a>.</p>

<p>Passwords are <b>not</b> stored, just the digest.</p>

<p>If you forget your password you can <a href="/users/password-reset">reset it</a>
so long as you know your user login name and the email address you
originally registered with. The system will send you an email with a
link you can use to set a new password.</p>
</div>
</body></html>
