<!DOCTYPE html>
<html>
<head>
$hackageCssTheme()$
<title>User accounts | Hackage</title>
</head>

<body>
$hackagePageHeader()$

<div id="content">
<h2>Create an account</h2>

<p>Fill in the <a href="/users/register-request">registration form</a> to get
a new user account for yourself.</p>

<p>Once you have your account you can upload packages with <em>new</em> names,
but not other existing packages.</p>

<p>If you want to upload a new version for a package uploaded by another user,
you should contact that user and request to be added to the package's
maintainer group.</p>

<h2>Upgrading an account from old Hackage</h2>

<p>Accounts have been imported from the old Hackage server however a one-time upgrade is required. Use the <a href="/users/htpasswd-upgrade">account upgrade</a> page. (If you don't know your username, <a href="/users/">the complete list</a> may help.)</p>


<h2>Account Management</h2>
<p>You can modify various settings for your account, including changing
  the password, as well as creating authentication
  tokens, at the <a href="/users/account-management">account
  management page</a>.</p>

<h2>Reset password</h2>
<p>If you forget your password you can <a href="/users/password-reset">reset it</a>
so long as you know your user login name and the email address you
originally registered with. The system will send you an email with a
link you can use to set a new password.</p>
</div>
</body></html>
