<!DOCTYPE html>
<html>
<head>
$hackageCssTheme()$
<title>User accounts | Hackage</title>
</head>

<body>
$hackagePageHeader()$

<div id="content">
<h2>User accounts</h2>
<h2>Create an account</h2>

<p>Fill in the <a href="/users/register-request">registation form</a> to get
a new user account for yourself.</p>

<p>Once you have your account you can upload packages with <em>new</em> names,
but not other existing packages.</p>

<p>If you want to upload a new version for a package uploaded by another user,
you should contact that user and request to be added to the package's
maintainer group.</p>

<p>Passwords are <b>not</b> stored, just the digest.</p>

<h2>Account Management</h2>
You can modify various settings for your account, including changing
  the email address and password, as well as creating authentication
  tokens, at the <a href="/users/account-management">page</a>.

<p>If you forget your password you can <a href="/users/password-reset">reset it</a>
so long as you know your user login name and the email address you
originally registered with. The system will send you an email with a
link you can use to set a new password.</p>
</div>
</body></html>
