name: "Test nix-shell"
on:
  - push
  - pull_request
jobs:
  nix-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/
    - uses: cachix/cachix-action@v10
      with:
        # https://nix.dev/tutorials/continuous-integration-github-actions#setting-up-github-actions
        name: hackage-server
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --pure --run "cabal update && cabal build all --enable-tests"
